{"level":"info","msg":"Wrapper started","pid":295,"time":"2022-01-07T12:54:04.969Z","wrapper":295}
{"level":"info","msg":"finding gitaly","pid":295,"pid_file":"/var/opt/gitlab/gitaly/gitaly.pid","time":"2022-01-07T12:54:04.969Z","wrapper":295}
{"level":"info","msg":"spawning a process","pid":295,"time":"2022-01-07T12:54:04.973Z","wrapper":295}
{"gitaly":331,"level":"info","msg":"monitoring gitaly","pid":295,"time":"2022-01-07T12:54:04.982Z","wrapper":295}
time="2022-01-07T12:54:05Z" level=info msg="Starting GitalyversionGitaly, version 14.6.1"
time="2022-01-07T12:54:05Z" level=warning msg="git path not configured. Using default path resolution" resolvedPath=/opt/gitlab/embedded/bin/git
{"latencies":[0.001,0.005,0.025,0.1,0.5,1,10,30,60,300,1500],"level":"info","msg":"grpc prometheus histograms enabled","time":"2022-01-07T12:54:05.585Z"}
{"level":"info","msg":"License database preloaded","time":"2022-01-07T12:54:09.535Z"}
{"level":"info","msg":"clearing disk cache object folder","storage":"default","time":"2022-01-07T12:54:09.540Z"}
{"level":"info","msg":"finished tempdir cleaner walk","storage":"default","time":"2022-01-07T12:54:09.540Z","time_ms":3}
{"level":"info","msg":"moving disk cache object folder to /var/opt/gitlab/git-data/repositories/+gitaly/tmp/diskcache2458943786","storage":"default","time":"2022-01-07T12:54:09.541Z"}
{"level":"info","msg":"disk cache object folder doesn't exist, no need to remove","storage":"default","time":"2022-01-07T12:54:09.542Z"}
{"level":"info","msg":"Starting file walker for /var/opt/gitlab/git-data/repositories/+gitaly/cache","path":"/var/opt/gitlab/git-data/repositories/+gitaly/cache","time":"2022-01-07T12:54:09.542Z"}
{"level":"info","msg":"Starting file walker for /var/opt/gitlab/git-data/repositories/+gitaly/state","path":"/var/opt/gitlab/git-data/repositories/+gitaly/state","time":"2022-01-07T12:54:09.542Z"}
{"level":"info","msg":"cleared all cache object files in /var/opt/gitlab/git-data/repositories/+gitaly/tmp/diskcache2458943786 after 408.605Âµs","storage":"default","time":"2022-01-07T12:54:09.543Z"}
{"level":"info","msg":"starting RSS monitor","supervisor.name":"gitaly-ruby.0","supervisor.rss_threshold":209715200,"time":"2022-01-07T12:54:10.150Z"}
{"level":"info","msg":"starting RSS monitor","supervisor.name":"gitaly-ruby.1","supervisor.rss_threshold":209715200,"time":"2022-01-07T12:54:10.151Z"}
{"level":"warning","msg":"spawned","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","331","/var/opt/gitlab/gitaly/internal_sockets/ruby.0"],"supervisor.name":"gitaly-ruby.0","supervisor.pid":356,"time":"2022-01-07T12:54:10.151Z"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.0 /var/opt/gitlab/gitaly/internal_sockets/ruby.0 \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.0: connect: connection refused\". Reconnecting...","pid":331,"system":"system","time":"2022-01-07T12:54:10.151Z"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1 /var/opt/gitlab/gitaly/internal_sockets/ruby.1 \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.1: connect: connection refused\". Reconnecting...","pid":331,"system":"system","time":"2022-01-07T12:54:10.151Z"}
{"level":"warning","msg":"spawned","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","331","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","supervisor.pid":357,"time":"2022-01-07T12:54:10.181Z"}
{"address":"/var/opt/gitlab/gitaly/gitaly.socket","level":"info","msg":"listening at unix address","time":"2022-01-07T12:54:10.189Z"}
{"address":"/var/opt/gitlab/gitaly/internal_sockets/internal_331.sock","level":"info","msg":"listening at unix address","time":"2022-01-07T12:54:10.194Z"}
{"address":"localhost:9236","level":"info","msg":"starting prometheus listener","time":"2022-01-07T12:54:10.223Z"}
{"level":"info","msg":"maintenance: daily scheduled","pid":331,"scheduled":"2022-01-08T12:00:00Z","time":"2022-01-07T12:54:10.224Z"}
{"level":"info","msg":"PID 356 BUNDLE_GEMFILE=/opt/gitlab/embedded/service/gitaly-ruby/Gemfile","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","331","/var/opt/gitlab/gitaly/internal_sockets/ruby.0"],"supervisor.name":"gitaly-ruby.0","time":"2022-01-07T12:54:10.558Z"}
{"level":"info","msg":"PID 357 BUNDLE_GEMFILE=/opt/gitlab/embedded/service/gitaly-ruby/Gemfile","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","331","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2022-01-07T12:54:10.624Z"}
{"gitaly":331,"level":"warning","msg":"forwarding signal","pid":295,"signal":15,"time":"2022-01-07T13:02:22.892Z","wrapper":295}
{"gitaly":331,"level":"warning","msg":"forwarding signal","pid":295,"signal":18,"time":"2022-01-07T13:02:22.973Z","wrapper":295}
{"error":"signal: killed","level":"warning","msg":"exited","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","331","/var/opt/gitlab/gitaly/internal_sockets/ruby.0"],"supervisor.name":"gitaly-ruby.0","time":"2022-01-07T13:02:24.405Z"}
{"error":"signal: killed","level":"warning","msg":"exited","supervisor.args":["bundle","exec","bin/ruby-cd","/var/opt/gitlab/gitaly","/opt/gitlab/embedded/service/gitaly-ruby/bin/gitaly-ruby","331","/var/opt/gitlab/gitaly/internal_sockets/ruby.1"],"supervisor.name":"gitaly-ruby.1","time":"2022-01-07T13:02:24.584Z"}
{"level":"warning","msg":"[transport] transport: http2Server.HandleStreams failed to read frame: read unix /var/opt/gitlab/gitaly/internal_sockets/internal_331.sock-\u003e@: use of closed network connection","pid":331,"system":"system","time":"2022-01-07T13:02:24.598Z"}
{"level":"warning","msg":"[core] grpc: addrConn.createTransport failed to connect to {unix:/var/opt/gitlab/gitaly/internal_sockets/internal_331.sock localhost \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/internal_331.sock: connect: no such file or directory\". Reconnecting...","pid":331,"system":"system","time":"2022-01-07T13:02:24.600Z"}
{"error":"received signal \"terminated\"","level":"error","msg":"shutting down","time":"2022-01-07T13:02:24.629Z"}
{"level":"info","msg":"Gitaly stopped","time":"2022-01-07T13:02:24.629Z"}
{"gitaly":331,"level":"warning","msg":"forwarding signal","pid":295,"signal":17,"time":"2022-01-07T13:02:25.300Z","wrapper":295}
{"error":"os: process already finished","gitaly":331,"level":"error","msg":"can't forward the signal","pid":295,"signal":17,"time":"2022-01-07T13:02:25.300Z","wrapper":295}
{"gitaly":331,"level":"error","msg":"wrapper for gitaly shutting down","pid":295,"time":"2022-01-07T13:02:26.174Z","wrapper":295}
